name: flutter_jp_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sficon: ^1.1.2
  google_fonts: ^6.2.1
  sf_symbols: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

  uses-material-design: true
  assets:
    - assets/detail/
    - assets/grafiken/
    - assets/background/
    - assets/snackish_ingredient_icons/
